# Generated by Django 5.0.6 on 2025-05-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nombre_comprador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
