# Generated by Django 5.2.1 on 2025-05-14 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_nombre_comprador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.PositiveBigIntegerField(max_length=100)),
                ('unidades', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
        ),
    ]
