# Generated by Django 5.2.1 on 2025-05-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_sucursal_venta_apellido_comprador_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='sucursal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
