# Generated by Django 5.2.1 on 2025-05-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_sucursal_id_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='id_sucursal',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre_sucursal',
            field=models.CharField(max_length=100),
        ),
    ]
