# Generated by Django 5.2.1 on 2025-05-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_pagada_venta_sucursal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='buy_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
