# Generated by Django 5.2.1 on 2025-05-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_sucursal_id_sucursal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='id_sucursal',
        ),
    ]
