# Generated by Django 5.2.3 on 2025-06-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocasamatriz',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='productos/'),
        ),
    ]
